---
apiVersion: v1
kind: Service
metadata:
  name: hello-1-svc
  annotations:
spec:
  selector:
    app: hello-1
  ports:
  - name: http
    protocol: TCP
    port: 3001

---
# Ambassador service mapping 
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: hello-1-mapping
spec:
  prefix: /
  service: hello-1-svc:3001